# Make sure to check your instance configuration before starting the server.
# Two instances of Rift using the same server-id will cause data persistence issues.
instance:
  proxy-id: 'NA'

# The interval (in seconds) in which this instance of Rift broadcasts updates to other Rift instances.
broadcast-update-interval: 3
