# Make sure to check your instance configuration before starting the server.
# Two instances of Rift using the same server-id will cause data persistence issues.
instance:
  proxy-id: 'NA'
  server-id: 'Hub-01'

# The interval (in seconds) in which this instance of Rift broadcasts updates to other Rift instances.
broadcast-update-interval: 3

# Prevents players from being able to join queues from this server
disable-queues: false

# Prevents default players from being able to join a queue via command
disable-queue-join-command: true

# Settings relating to the spoofing mechanic
spoof:
  load-profiles: true
  enabled: false
  paused: false
  multiplier: 2.0 # The factor to multiply the real player count by
  min: 10
  max: 100
  buffer: 10
  interval: 20
  min-delay: 1000L
  max-delay: 3500L
  # Settings relating to making fake players join queues
  queues:
    NONE: 0
    prison: 100
  # Settings relating to making fake players look real
  realism:
    # Assigning ranks to fake players
    # rank id -> chance
    rank-assignment: {}
    # Making fake players perform actions
    actions: {}